---
version: '3.8'
services:

  mysql:
    image: x0rzkov/mysql-multi:5-ubuntu
    build:
      context: .docker/storage/mysql5-multi
      dockerfile: Dockerfile
    container_name: ${NAMESPACE}-multidb
    ports:
    - 3308:3306
    volumes:
    - db-data:/var/lib/mysql
    networks:
    - internal
    - web
    environment:
      MYSQL_MULTIPLE_DATABASES: stargazers
      MYSQL_PASSWORD: ${STARGAZER_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${STARGAZER_MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${STARGAZER_MYSQL_USER}
    restart: unless-stopped

networks:
  internal:
    driver: bridge
  web:
    external: true

volumes:
  db-data:
